name: Hapus File Selain Index

on:
  workflow_dispatch:

jobs:
  delete-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          ref: main

      - name: Hapus semua file kecuali index.html
        run: |
          rm -f *.html
          git restore index.html

      - name: Commit perubahan
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add -A
          git commit -m "Hapus semua file kecuali index.html" || echo "Tidak ada perubahan"
          git push origin main
